---
resource_types:
  - name: email
    type: docker-image
    source:
      repository: pcfseceng/email-resource

resources:
  - name: blog
    type: git
    icon: github-circle
    check_every: 10m 
    source:
      uri: https://github.com/devulrix/blog.git
      branch: master
  
  - name: hugo-release
    type: github-release
    icon: github-circle
    check_every: 10m 
    source:
      owner: gohugoio
      repository: hugo

  - name: send-an-email
    type: email
    icon: email
    source: 
      from: ((mail-from))
      smtp: 
        host: ((mail-host))
        port: ((mail-port))
        username: ((mail-user))
        password: ((mail-password))
      to: [ ((mail-recipient)) ]

jobs:
- name: build and push
  plan:
  - get: blog
    trigger: true
  - get: hugo-release
    version:
      {tag: 'v0.67.0'}
    params:
      globs:
      - hugo_[0-9].*_Linux-64bit.tar.gz
  - task: build-hugo
    file: blog/ci/tasks/build-hugo.yml
  - task: ftp-push
    file: blog/ci/tasks/ftp-push.yml
    params:
      FTP_SERVER: ((ftp-server))
      FTP_USERNAME: ((ftp-user))
      FTP_PASSWORD: ((ftp-password))
  on_error:
     do:
      - put: send-an-email
        params:
          body_text: 'Build error in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'
          subject_text: 'Build error in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'
  on_failure:
    do:
      - put: send-an-email
        params:
          body_text: 'Build failure in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'
          subject_text: 'Build failure in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}' 

